require("./js/egret.min.js")
require("./js/eui.min.js")
require("./js/assetsmanager.min.js")
require("./js/tween.min.js")
require("./js/main.js")
require("./js/default.thm.js")
require("./js/game.min.js")